output_path: "data/output_test_test_test.csv"

data_paths:
  route_info: "data/raw/route_info_test.csv"
  track_info: "data/raw/track_info_test.csv"
gps_params:
  max_speed: 150         # км/ч
  max_accel: 15          # м/с²
  min_cluster_ratio: 0.7
  warmup_points: 10
  stability_threshold: 7

event_params:
  radius: 250            # метров
  min_stop_time: 300     # секунд (5 минут)
  confirmation_time: 300 # секунд (1 минута)
  max_speed_in_zone: 25   # км/ч
  reentry_window: 300
  next_order_window: 0

cities:
  NSK:
    timezone: Asia/Novosibirsk
    default_radius: 100
  YR:
    timezone: Europe/Moscow
    default_radius: 80
  YSP:
    timezone: Europe/Moscow
    default_radius: 80