gps_params:
  max_speed: 150         # км/ч
  max_accel: 15          # м/с²
  min_cluster_ratio: 0.7
  warmup_points: 50
  stability_threshold: 5

event_params:
  radius: 100            # метров
  min_stop_time: 300     # секунд (5 минут)
  confirmation_time: 60  # секунд (1 минута)
  max_speed_in_zone: 7   # км/ч

cities:
  NSK:
    timezone: Asia/Novosibirsk
    default_radius: 100
  YR:
    timezone: Asia/Yekaterinburg
    default_radius: 120
  YSP:
    timezone: Europe/Saint-Petersburg
    default_radius: 80